projects:
  redznake-api:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
      - src/app/API.service.ts
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: eu-west-1
        apiId: gvgdf3okhbfgtgyrm237tem3ie
        maxDepth: 3
extensions:
  amplify:
    version: 3
